import CreateNote from "@/components/create-note";

export default function Home() {
  return (
    <div>
      <CreateNote />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
      Some text
      <br />
    </div>
  );
}
